language: node_js
node_js:
  - 12
services:
  - mysql
sudo: true
before_script:
  - chmod +x ./travis/*
  - ./travis/mysql-reset-root-password.sh
  - ./travis/create-test-database.sh

script:
  - standard
  - npm run test:coveralls
env:
  - APP_SECRET=dhaowhuafawjfioa

